version: '3.8'

services:
  web:
    build:
      context: .  
      dockerfile: DevSkill.Inventory.Web/Dockerfile  
    ports:
      - "8000:80"  
    volumes:
      - ./Logs:/app/Logs  
    depends_on:
      - worker  
    env_file:
      - DevSkill.Inventory.Web/web.env  

  worker:
    build:
      context: .  
      dockerfile: DevSkill.Inventory.Worker/Dockerfile  
    volumes:
      - ./Logs:/app/Logs 
    entrypoint: ["dotnet", "DevSkill.Inventory.Worker.dll"]  
    env_file:
      - DevSkill.Inventory.Worker/worker.env  

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Logs  

